### ISSUE TITLE
More descriptive error messages 

### ISSUE THREAD

**Issue by VitorEstevam** [neo7337/go-struct-validator#14]
Today we have error messages saying what verification failed. As we have the expected value and the actual value we can create better error messages. I can do this improvement :D 

actual error message:

```"max value validation failed"```

Expected error message:

```"max value validation failed for field 'Size'. The value is 21, but the expected maximum is 20"```

**Comment by neo7337** [comment]
yeah we can improve on this, happy to take a PR on this one @VitorEstevam

**Comment by VitorEstevam** [comment]
i`m starting to work on this ;)

**Comment by neo7337** [comment]
good to close this issue, thanks @VitorEstevam
